[package]
name = "simd_examples"
version = "0.1.0"
authors = ["Dustin Bensing <dustin.bensing@googlemail.com>"]

[dependencies]
orbclient = "0.3.12"
orbimage = "0.1.15"
stdsimd = { git = "https://github.com/rust-lang-nursery/stdsimd" }
time = "0.1.38"

[profile.release]
debug = true